server:
  port: 10900
  tomcat:
    accept-count: 500
    uri-encoding: UTF-8
    threads:
      max: 500 #最大线程数
      min-spare: 20 #最小空闲线程数

spring:
  redis:
    host: redis-dev-master.dev-common.svc.cluster.local
    port: 6379
    password: q970J4RvjH
    database: 6
    timeout: 300000 #连接超时时间（毫秒）
    connectTimeout: 300000 #连接超时时间（毫秒）
